language: node_js
env:
  global:
  - secure: "QzDieB3Amjfp9I0pOjr8hkfcl3C2mEh9RJBzOoZJwBGOzsuF7+DhViuRMcyNxTZniXutsWrMGlnG2B+HfttGjupMydWjmVLjcuxSlFyvitI5xa0YLhrCoA1w2gMlWkRTlcbKslCzynxlhHr+jhLuZfi+bAkIZfukvnmK1zkgt7FvmSjp2aeXCm7Hbm8mXmsRqPcRxkQJ6R7aTumyDXvFX+fkXf0cI4bq+/ox3LUm8ym+47/z642tBTmnCaTxS5dbJynEamTiTOwcyVj+PKBzyiy3XUwRL+ggHkTsNpnouCnfOTOcTWaS2plfGRjonbionSPwyTAoLskTZKRaZUqkhuEecoPSt/5qE6MLMuP/X5krsQk2mn4tRRDAAJozWFEJnQ06DlLmpVSbZMKK3EUbSSVF63H2WYMFdEeQrINc66cWMQhyXgQFrnmgdwVit+xOaX010xHN9Lb2qC9aaxwH+FdSOqgvmDsGSUVuviaYHhH5RhwKCNfLY/h7UeAqn2d4sPcSUwYPi61ZheXW3KPF9cxTGH6A5SVRnccv+SDS5xJLPDpoN4jujHfraPTT8EE/MEZPJm4NpmTEvBxlNW+ALNDvTmGI/U0UJUfUqc2VE9Wnu9BXyxuEkFBp4nUFOCIVb66EhG22VFjycFpVzAd6j5cBcCncvOVYCRa0JDMuT9w="
node_js:
  - "stable"
before_install:
  - gem install compass
  - gem install susy
install: npm install
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - grunt build
after_success:
  - eval "$(ssh-agent -s)" # start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - cd dist
  - git init
  - git config --global user.email "michael@kleinhenz.net"
  - git config --global user.name "michaelkleinhenz"
  - git add .
  - git commit -a -m "Build Commit"
  - git push -u origin --all --force
  - git push --force --quiet "https://${GH_TOKEN}@github.com/michaelkleinhenz/storyquest-builds.git" master
